# @package _global_


model:
  _target_: src.models.mmr.MMR
  _partial_: True
  num_continuous: ${data.num_continuous}
  num_binary: ${data.num_binary}
  cross_fitting_seed: 42
  ihdp: ${data.ihdp}
  obs_dict: ${data.obs_dict}