# @package _global_

defaults:
  - censoring_default
  - propensity_default
  - selection_default
  - response_surface_default
  - defaults

model: 
  kernel: laplace
  censoring_type: ${data.censoring_type}
  phi1_as_phi0: True #Use the same estimator for phi1 and phi0