# @package _global_

defaults:
  - censoring_default
  - event_default
  - propensity_default
  - selection_default
  - response_surface_default
  - defaults

model: 
  kernel: laplace
  censoring_type: ${data.censoring_type}
  propensity_weighting_for_phi1: ${propensity_weighting_for_phi1} #Use the same estimator for phi1 and phi0