# @package _global_

model:
  propensity_model:
    model_name: GradientBoostingClassifier
    hp:
      learning_rate: [0.01]
      n_estimators: [50]
      max_depth: [2]
      min_samples_leaf: [50]
      min_samples_split: [50]
      max_features: ['sqrt']
      random_state': [42]
    model_type: binary 